project:
  type: book

book:
  title: "Labor Economics"
  author: "David Arnold"
  date: "2/23/2025"
  sidebar:
    collapse-level: 2
  chapters:
  - part: "Main Text"
    chapters:
    - index.qmd
    - 01.qmd
    - 02.qmd
    - 03.qmd
    - 04.qmd
    - 05.qmd
    - 06.qmd
    - 07.qmd
    - 08.qmd
    - 09.qmd
    - 10.qmd
    - references.qmd
  - part: "Datasets"
    chapters:
    - cps.qmd
    - acs.qmd
    - onet.qmd
  

bibliography: references.bib

format:
  html:
    theme: [default, theme-light.scss]
    css: [styles.css, vermilion.css]
    toc-title: "In this chapter"
    grid:
      body-width: 680px
      sidebar-width: 205px
      margin-width: 170px
      gutter-width: 2rem
    fig-align: center
    include-before-body: _includes/masthead.html
    include-after-body: _includes/after-body.html
    js: lightbox.js
  pdf:
    documentclass: scrreprt



